### PR TITLE
Update unit test to account for invalid/missing windows event type

### PR DESCRIPTION
**Pull request by dbouchillon**
Fixes ZPS-2453

### CODE REVIEW

**Comment by dbouchillon** [comment]
the check failed due to an error that occurred when building the egg, not during unit tests:  "fabric.exceptions.NetworkError: Host key for localhost did not match pre-existing key! Server's key was changed recently, or possible man-in-the-middle attack."

the runtests job restarted and succeeded: 
 http://jenkins.zenosslabs.com/view/Run%20Unit%20Tests/job/Microsoft.Windows-RunTests/236/

**Comment by addjuarez** [comment]
I think you can retry the check, let me see

**Comment by addjuarez** [comment]
retest this please

**Comment by dbouchillon** [comment]
bump

**Pull request merged**
